name: WildApricot Daily CRON job

on:
  schedule:
    - cron: '0 10 * * *'
jobs:
  build:
    name: FTP Processing HTTP Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      - name: HTTP Request Action
        uses: fjogeleit/http-request-action@v1.11.1
        with:
          url: 'http://sbnew-publi-1o4nxb30frlxf-351362560.us-east-2.elb.amazonaws.com/newbieToNewcomer'
          method: 'GET'
          contentType: 'application/json'
          timeout: 60000
